@startuml "CUN-03: Gestionar Identidad"
left to right direction

skinparam usecase {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam actor {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam Arrow {
  Color #7A1631
}

actor "Dueño de PYME / Consultor" <<Business Actor>> as user

usecase "CUN-03: Gestionar Identidad\ny Perfiles de Usuario" as cun3

user --> cun3
@enduml