@startuml

actor "Usuario B2B"  as user


rectangle "Web App\n\nInterfaz para carga de archivos, \nconfiguración de metadatos y\n chat analítico." as web

rectangle "Backend & API Gateway\n\nOrquestador central.\nGestiona archivos en memoria,\nconexiones a BD y ejecuta consultas." as api

rectangle "AI Analytics Agent\n\nMotor IA que traduce lenguaje natural\na código (SQL/Python),sugiere gráficos y\nredacta insights." as ai

database "Base de Datos\n\nAlmacena perfiles, workspaces,\nesquemas guardados y el historial." as db


user ..> web : Sube CSV / Conecta BD\ny realiza preguntas analíticas

web ..> api : Solicita análisis \n y envía prompt

api ..> ai : Envía prompt y \nmetadatos
ai ..> api : Devuelve código,\nconfiguración de gráfico \ne insights

api ..> db : Recuperar Información \ndel Cliente
db ..> api : Retorna datos de \nla consulta

api ..> web : Envía datos estructurados,\ngráfico e insight narrativo

@enduml