@startuml "CUN Global"
left to right direction

actor/ "Dueño de PYME" <<Business Actor>> as pyme
actor/ "Consultor" <<Business Actor>> as consultor

rectangle "Contexto de Negocio: PYMENET SaaS" {
  usecase/ "CUN-01: Consultar datos\nmediante lenguaje natural" as cun1
  usecase/ "CUN-02: Gestionar Entornos\nde Trabajo y Reportes" as cun2
}

pyme --> cun1
consultor --> cun1
consultor --> cun2

skinparam usecase {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam actor {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam Arrow {
  Color #7A1631
}
@enduml